### ISSUE TITLE
No license information

### ISSUE THREAD

**Issue by coroa** [wertarbyte/autorandr#24]
i'm currently packaging autorandr for nixos and am stumbling over the fact, that there is no information on the code's license provided. legally this results in prohibiting any modification or distribution.

http://choosealicense.com/ sums it up rather nicely.

**Comment by nomeata** [comment]
I was considering packaging this for Debian, but we also need license information.

**Comment by wertarbyte** [comment]
After a while, I finally got around to this - licence should be GPLv3, so feel free to package :-)
