### ISSUE TITLE
Does not save all xrandr options

### ISSUE THREAD

**Issue by deevus** [wertarbyte/autorandr#42]
I have the following custom xrandr script

```
xrandr \
    --output eDP-1 \
    --auto \
    --dpi 160 \
    --output DP-3-2 \
    --auto \
    --dpi 96 \
    --right-of eDP-1 \
    --scale 1.4x1.4 \
    --panning 5376x3024+2560+0
```

The output of this config for autorandr is this:

```
output eDP-1
mode primary
pos x
rotate 2560x1440+0+0
output DP-1
off
output HDMI-1
off
output DP-2
off
output HDMI-2
off
output DP-3
off
output HDMI-3
off
output DP-3-2
mode 5376x3024
pos 2560x0
output DP-3-1
off
output DP-3-3
off
```

The autorandr configuration seems to be missing the `scale` and `dpi` options.

**Comment by phillipberndt** [comment]
Please have a look at my fork where this issue has been fixed. This repository is unmaintained.

**Comment by deevus** [comment]
Ok thank you @phillipberndt I'll give it a go

**Comment by deevus** [comment]
@phillipberndt Seems to work. I'll be sure to let you know if I have any problems :joy:
