### ISSUE TITLE
Toggle between profiles

### ISSUE THREAD

**Issue by linoman** [wertarbyte/autorandr#43]
This is not an issue but rather a question.

Is it possible to rotate/toggle between available profiles?

**Comment by phillipberndt** [comment]
Please check #36, this is possible in the maintained fork: It'll update a loaded profile's mtime whenever it loads one, and sort the list of profiles by mtime (in descending order) when loading them. This is the wrong way around for you, but you should be able to write yourself a `block` hook and check for the position in the `AUTORANDR_CURRENT_PROFILES` environment variable to add this behaviour.
