### ISSUE TITLE
Doesn't seem save refresh rate

### ISSUE THREAD

**Issue by quite** [wertarbyte/autorandr#6]
autorandr doesn't save the refresh rate, does it?

**Comment by alpar-t** [comment]
I confirm, my monitor doesn't work @60 and doesn't set it to @30

**Comment by phillipberndt** [comment]
Does this patch work? https://github.com/phillipberndt/autorandr/tree/rate

Also, see https://github.com/wertarbyte/autorandr/pull/29

**Comment by alpar-t** [comment]
Yes it does. Thank you very much !

**Comment by phillipberndt** [comment]
Merged to https://github.com/phillipberndt/autorandr
